name: Supabase DB Backup

on:
  schedule:
    - cron: "0 17 * * *"   # ~01:00 AM Asia/Manila
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: Install pg client
        run: sudo apt-get update && sudo apt-get install -y postgresql-client

      - name: Dump database (IPv4 + SSL)
        env:
          DATABASE_URL: ${{ secrets.SUPABASE_DB_URL }}
        run: |
          set -e
          URI="$DATABASE_URL"
          HOST=$(echo "$URI" | sed -E 's#.*@([^:/?]+).*#\1#')
          PORT=$(echo "$URI" | sed -E 's#.*:([0-9]+)/.*#\1#')
          DB=$(echo "$URI"   | sed -E 's#.*/([^/?]+).*#\1#')
          USER=$(echo "$URI" | sed -E 's#postgresql://([^:]+):.*#\1#')
          PASS=$(echo "$URI" | sed -E 's#postgresql://[^:]+:([^@]+)@.*#\1#')

          # Force IPv4 to avoid IPv6 “Network is unreachable”
          ADDR=$(getent ahostsv4 "$HOST" | awk '{print $1; exit}')
          echo "Resolved $HOST -> $ADDR"

          CONN="hostaddr=$ADDR host=$HOST port=$PORT dbname=$DB user=$USER password=$PASS sslmode=require"

          mkdir -p backups
          TS=$(date -u +"%Y-%m-%dT%H-%M-%SZ")
          pg_dump "$CONN" --schema-only > "backups/schema_$TS.sql"
          pg_dump "$CONN" --data-only  > "backups/data_$TS.sql"
          tar -czf "supabase-backup_$TS.tar.gz" -C backups .
          rm -rf backups

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: supabase-backup
          path: supabase-backup_*.tar.gz
          retention-days: 7
