# .github/workflows/backup.yml
name: Supabase DB Backup

on:
  schedule:
    - cron: "0 17 * * *"   # ~01:00 AM Asia/Manila
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: Install pg client
        run: sudo apt-get update && sudo apt-get install -y postgresql-client

      - name: Dump database (Supavisor IPv4 pooler)
        env:
          DATABASE_URL: ${{ secrets.SUPABASE_DB_URL }}
        run: |
          set -e
          if [ -z "$DATABASE_URL" ]; then
            echo "ERROR: SUPABASE_DB_URL secret is missing"; exit 1
          fi
          # Guard: fail fast if you accidentally pasted a Direct (IPv6) host
          HOST=$(echo "$DATABASE_URL" | sed -E 's#.*@([^:/?]+).*#\1#')
          case "$HOST" in
            *.pooler.supabase.com) echo "Using Supavisor pooler (IPv4): $HOST" ;;
            *) echo "ERROR: Your URL host is '$HOST' (Direct/IPv6). In CI use Supavisor Session mode from Connect."; exit 1 ;;
          esac

          export PGSSLMODE=require
          mkdir -p backups
          TS=$(date -u +"%Y-%m-%dT%H-%M-%SZ")
          pg_dump "$DATABASE_URL" --schema-only > "backups/schema_$TS.sql"
          pg_dump "$DATABASE_URL" --data-only  > "backups/data_$TS.sql"
          tar -czf "supabase-backup_$TS.tar.gz" -C backups .
          rm -rf backups

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: supabase-backup
          path: supabase-backup_*.tar.gz
          retention-days: 7
