name: Supabase DB Restore

on:
  workflow_dispatch:
    inputs:
      artifact_id:
        description: "Backup artifact ID to restore"
        required: true
      target:
        description: "Restore target"
        type: choice
        options: [staging, production]
        default: staging

jobs:
  restore:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client unzip

      - name: Pick target DB URL
        id: pick
        run: |
          if [ "${{ github.event.inputs.target }}" = "production" ]; then
            echo "dburl=${{ secrets.RESTORE_DB_URL_PROD }}" >> $GITHUB_OUTPUT
          else
            echo "dburl=${{ secrets.RESTORE_DB_URL_STAGING }}" >> $GITHUB_OUTPUT
          fi

      - name: Download artifact by ID
        run: |
          set -e
          ID="${{ github.event.inputs.artifact_id }}"
          curl -sSL -H "Authorization: Bearer $GH_TOKEN" \
               -H "X-GitHub-Api-Version: 2022-11-28" \
               -o artifact.zip \
               "https://api.github.com/repos/${{ github.repository }}/actions/artifacts/$ID/zip"
          unzip -q artifact.zip -d artifact
          ls -l artifact

      - name: Extract SQLs
        run: |
          set -e
          mkdir -p backup
          TARBALL=$(ls artifact/supabase-backup_*.tar* | head -n1)
          if [[ "$TARBALL" == *.tar.gz ]]; then
            tar -xzf "$TARBALL" -C backup
          else
            tar -xf "$TARBALL" -C backup
          fi
          ls -l backup

      - name: Restore schema then data
        env:
          DBURL: ${{ steps.pick.outputs.dburl }}
        run: |
          set -e
          if [ -z "$DBURL" ]; then echo "ERROR: target DB URL secret is missing"; exit 1; fi
          export PGSSLMODE=require
          psql "$DBURL" -f backup/schema_*.sql
          psql "$DBURL" -f backup/data_*.sql
